citas = new Array(4)
citas[0] = "2271. A Igreja afirmou, desde o século I, a malícia moral de todo o aborto provocado. E esta doutrina não mudou. Continua invariável. O aborto directo, isto é, querido como fim ou como meio, é gravemente contrário à lei moral:«Não matarás o embrião por meio do aborto, nem farás que morra o recém-nascido» (47).«Deus [...], Senhor da vida, confiou aos homens, para que estes desempenhassem dum modo digno dos mesmos homens, o nobre encargo de conservar a vida. Esta deve, pois, ser salvaguardada, com extrema solicitude, desde o primeiro momento da concepção; o aborto e o infanticídio são crimes abomináveis» (48).2272. A colaboração formal num aborto constitui falta grave. A Igreja pune com a pena canónica da excomunhão este delito contra a vida humana. «Quem procurar o aborto, seguindo-se o efeito («effectu secuto») incorre em excomunhão latae sententiae (49), isto é, «pelo facto mesmo de se cometer o delito» (50) e nas condições previstas pelo Direito (50). A Igreja não pretende, deste modo, restringir o campo da misericórdia. Simplesmente, manifesta a gravidade do crime cometido, o prejuízo irreparável causado ao inocente que foi morto, aos seus pais e a toda a sociedade.\n\nCatecismo da Igreja Católica."

citas[1] = "“Os bens do mundo têm somente aparência de bens, é por isso que não podem saciar o coração do homem. O mesmo acontece com o ambicioso, que quer saciar-se com uma fumaça. Se os bens da terra pudessem contentar o homem, os ricos, os monarcas seriam perfeitamente felizes, mas a experiência prova o contrário. É o que Salomão declara, afiançando-nos que nada tinha negado aos sentidos: ‘Vaidade das vaidades, é tudo vaidade’.”\n\nSanto Afonso de Ligório."
citas[2] = "A comunhão diária não pode conviver com o desejo de aparecer, vaidade no vestir, prazeres da gula, comodidades, conversas frívolas e maldosas. Exige oração, mortificação, recolhimento. Ficai certos de que todos os instantes da vossa vida, o tempo que passardes diante do Divino Sacramento será o que vos dará mais força durante a vida, mais consolação na hora da morte e durante a eternidade.\n\nSanto Afonso de Ligório"
citas[3] = "Vamos, coragem, pobre homem! Foge um pouco de tuas ocupações. Esconde-te um instante do tumulto de teus pensamentos. Põe-te de parte dos cuidados que te absorvem e livra-te das preocupações que te afligem. Dá um pouco de tempo a Deus e repousa nele.\n\nSanto Anselmo"
citas[4] = "A esperança tem duas filhas lindas, a indignação e a coragem; a indignação nos ensina a não aceitar as coisas como estão; a coragem, a mudá-las.\n\nSanto Agostinho"
citas[5] = "As pessoas costumam amar a verdade quando esta as ilumina, porém tendem a odiá-la quando as confronta.Santo Agostinho"
citas[6] = "O socialismo ergue-se sobre as bases da cobiça, ou seja, uma transgressão do nono e décimo Mandamentos."
citas[7] = "2425. A Igreja rejeitou as ideologias totalitárias e ateias, associadas, nos tempos modernos, ao «comunismo» ou ao «socialismo». Por outro lado, recusou, na prática do «capitalismo», o individualismo e o primado absoluto da lei do mercado sobre o trabalho humano (167). Regular a economia só pela planificação centralizada perverte a base dos laços sociais: regulá-la só pela lei do mercado é faltar à justiça social, «porque há numerosas necessidades humanas que não podem ser satisfeitas pelo mercado» (168). É necessário preconizar uma regulação racional do mercado e das iniciativas económicas, segundo uma justa hierarquia dos valores e tendo em vista o bem comum."
citas[8] = "Eu Vos amo, Deus infinitamente bom, e mais quero morrer amando-Vos do que viver um só instante sem Vos amar. Eu Vos amo, meu Deus, e só desejo o Céu para ter a felicidade de Vos amar perfeitamente.Eu Vos amo, meu Deus, e só temo o inferno porque lá nunca haverá a doce consolação de Vos amar. Meu Deus, se a minha língua não puder estar sempre a dizer que Vos amo, que o meu coração o diga tantas vezes como quantas eu respiro. Senhor, dai-me a graça de sofrer amando-Vos, de Vos amar sofrendo, e de um dia expirar amando-Vos e sentindo que Vos amo. E quanto mais me aproximo do meu fim, mais Vos imploro a graça de aumentar e aperfeiçoar o meu amor. Amém."
citas[9] = "O Sacerdote não é para si, mas para vós…"
citas[10] = "9.Acaso não sabeis que os injustos não hão de possuir o Reino de Deus? Não vos enganeis: nem os impuros, nem os idólatras, nem os adúlteros, nem os efeminados, nem os devassos, 10.nem os ladrões, nem os avarentos, nem os bêbados, nem os difamadores, nem os assaltantes hão de possuir o Reino de Deus. I Coríntios 6, 9-10"
citas[11] = "A devoção a eucaristia é a mais nobre de todas as devoções, porque tem o próprio Deus por objeto; é a mais salutar porque nos dá o próprio autor da Graça; é a mais suave porque suave é o Senhor. Se os anjos pudessem sentir inveja, nos invejaríamos porque podemos comungar."
citas[12] = "Para um cristão, o matrimônio não é uma simples instituição social, e menos ainda um remédio para as fraquezas humanas: é uma autêntica vocação sobrenatural. Sacramento grande em Cristo e na Igreja, diz São Paulo, e, ao mesmo tempo e inseparavelmente, contrato que um homem e uma mulher estabelecem para sempre, porque - queiramos ou não - o matrimônio instituído por Jesus Cristo é indissolúvel: sinal sagrado que santifica, ação de Jesus que se apossa da alma dos que se casam e os convida a segui-Lo, transformando toda a vida matrimonial em um caminhar divino sobre a terra. —  Josemaría Escrivá de Balaguer"
citas[13] = "Faz-me santo, meu Deus, ainda que seja à paulada...  Josemaría Escrivá de Balaguer"
citas[14] = "O grande plano do amor de Deus é a redenção e a salvação de todos os Homens pelo seu Filho Jesus Cristo. A Igreja existe porque Jesus nos convidou para estarmos com Ele numa profunda e redentora comunhão. Esta comunidade, o 'corpo de Cristo', é a Igreja. Pelo batismo e pelos outros sacramentos pertencemos a Cristo e por Ele recebemos uma vida nova e eterna. Pela escuta da Palavra de Deus, seguimos a sua vontade. A Igreja é o lugar no qual o Homem pode desenvolver-se no amor de Deus. A Igreja não tem um fim em si mesma. Ela é responsável pelo Homem e pela sociedade e deve com a sua acção contribuir para a paz e o desenvolvimento da família humana."
citas[15] = "Deus, afastar-me de ti significa falhar. Voltar a ti significa levantar. Ficar contigo é ter abrigo. - Santo Agostinho"
  citas[16] = " Acreditar na família é construir o futuro. Papa João Paulo II" 
   citas[17] = "Os jovens estão chamados a serem os protagonistas dos novos tempos. Tenho plena confiança neles e estou certo de que têm a vontade de não defraudar nem a Deus, nem à Igreja, nem à sociedade da que provêm. Papa João Paulo II"
    citas[18] = "Eu posso contribuir apenas com uma gota de água para o oceano mas, com minha gota, ele jamais será o mesmo. Madre Teresa de Calcutá"
     citas[19] = "Não seja conduzido pela voz de seus medos e decepções; seja conduzido por seus sonhos e pela voz de Deus que quer sempre falar em seu coração. Padre Adriano Zandoná"
      citas[20] = "Comece fazendo o que é necessário, depois o que é possível, e de repente você estará fazendo o impossível. São Francisco de Assis" 

       citas[21] = "Virgem das virgens, Rainha, Mãe de Deus, Senhora minha: Chorar convosco é rezar. Cada lágrima chorada Lembra uma estrela tombada Do fundo do vosso olhar. No Calvário, entre martírios, Fostes o Lírio dos lírios, Todo orvalhado de pranto. Sobre o ódio que O matava, Fostes o Amor que adorava O Filho três vezes santo. A cruz do Senhor me guarde, De manhã até à tarde, A minha alma contrita. E quando a morte chegar, Que eu possa ir repousar À sua sombra bendita."
        citas[22] = " Ef 1, 3-10 - O plano divino da salvação  Bendito seja Deus, *     Pai de Nosso Senhor Jesus Cristo, que do alto do Céu nos abençoou, *     com todas as bênçãos espirituais em Cristo.  Ele nos escolheu, antes da criação do mundo, *     para sermos santos e irrepreensíveis, †     em caridade, na sua presença. Ele nos predestinou, de sua livre vontade, *     para sermos seus filhos adoptivos, por Jesus Cristo,  para que fosse enaltecida a glória da sua graça, *     com a qual nos favoreceu em seu amado Filho; n’Ele temos a redenção, pelo seu Sangue, *     a remissão dos nossos pecados;  segundo a riqueza da sua graça, *     que Ele nos concedeu em abundância, com plena sabedoria e inteligência, *     deu-nos a conhecer o mistério da sua vontade:  segundo o beneplácito que n’Ele de antemão estabelecera, *     para se realizar na plenitude dos tempos: instaurar todas as coisas em Cristo, *     tudo o que há nos céus e na terra."
         citas[23] = "Estava a Mãe dolorosa, Junto da cruz, lacrimosa, Enquanto Jesus sofria.  Uma longa e fria espada, Nessa hora atribulada, O seu coração feria.  Oh quão triste e quão aflita Padecia a Mãe bendita, Entre blasfémias e pragas,  Ao olhar o Filho Amado, De pés e braços pregado, Sangrando das Cinco Chagas! Quem é que não choraria, Ao ver a Virgem Maria, Rasgada em seu coração,  Sem poder, em tal momento, Conter as fúrias do vento E os ódios da multidão!  Firme e heróica no seu posto, Viu Jesus, pendendo o rosto, Soltar o alento final.  Ó Cristo, por vossa Mãe, Que é nossa Mãe também, Dai-nos a palma imortal."
          citas[24] = "Senhor Deus de Paz, escutai a nossa súplica!Tentámos tantas vezes e durante tantos anos resolver os nossos conflitos com as nossas forças e também com as nossas armas; tantos momentos de hostilidade e escuridão; tanto sangue derramado; tantas vidas despedaçadas; tantas esperanças sepultadas... Mas os nossos esforços foram em vão. Agora, Senhor, ajudai-nos Vós! Dai-nos Vós a paz, ensinai-nos Vós a paz, guiai-nos Vós para a paz. Abri os nossos olhos e os nossos corações e dai-nos a coragem de dizer: «nunca mais a guerra»; «com a guerra, tudo fica destruído»! Infundi em nós a coragem de realizar gestos concretos para construir a paz. Senhor, Deus de Abraão e dos Profetas, Deus Amor que nos criastes e chamais a viver como irmãos, dai-nos a força para sermos cada dia artesãos da paz; dai-nos a capacidade de olhar com benevolência todos os irmãos que encontramos no nosso caminho. Tornai-nos disponíveis para ouvir o grito dos nossos cidadãos que nos pedem para transformar as nossas armas em instrumentos de paz, os nossos medos em confiança e as nossas tensões em perdão. Mantende acesa em nós a chama da esperança para efectuar, com paciente perseverança, opções de diálogo e reconciliação, para que vença finalmente a paz. E que do coração de todo o homem sejam banidas estas palavras: divisão, ódio, guerra! Senhor, desarmai a língua e as mãos, renovai os corações e as mentes, para que a palavra que nos faz encontrar seja sempre «irmão», e o estilo da nossa vida se torne: shalom, paz, salam! Amen."
 
citas[25]= "(Ecl 1,2-11) “Vaidade das vaidades, diz o Eclesiastes, vaidade das vaidades! Tudo é vaidade”. Que proveito tira o homem de todo o trabalho com o qual se afadiga debaixo do sol? Uma geração passa, outra lhe sucede, enquanto a terra permanece sempre a mesma. O sol se levanta, o sol se deita, apressando-se para voltar a seu lugar, donde novamente torna a levantar-se. Dirigindo-se para o sul e voltando para o norte, ora para cá, ora para lá, vai soprando o vento, para retomar novamente o seu curso. Todos os rios correm para o mar, e contudo o mar não transborda; voltam ao lugar de onde saíram para tornarem a correr. Tudo é penoso, difícil para o homem explicar. A vista não se cansa de ver, nem o ouvido se farta de ouvir. O que foi será; o que aconteceu, acontecerá: 10não há nada de novo debaixo do sol. Uma coisa da qual se diz: “Eis aqui algo de novo”, também esta já existiu nos séculos que nos precederam. Não há memória do que aconteceu no passado, nem também haverá lembrança do que acontecer, entre aqueles que viverão depois."
citas[26] = "“É pela Cruz que se dá a bênção, é por ela que Deus nos perdoa e concede remissão. Ele quer que todas as coisas tragam este selo, sem o qual nada lhe parece belo.” São Luís Maria Grignion de Montfort"
citas[27] = "“A devoção a Maria é um meio excelente de promover a maior glória de Deus. Maria, a quem entregamos o valor de nossas boas obras, sabe perfeitamente em que consiste a maior glória de Deus, e nada faz que não contribua para este fim.” São Luís Maria Grignion de Montfort"
citas[28] = "Espero no dia do meu julgamento ouvir essas palavras: 'Ouvi minha Mãe falar de ti.' -Fulton Sheen"
citas[29] = "...A Igreja precisa se opor às 'marés' de modismos e das últimas novidades....Papa Bento XVI"
citas[30] = "Quem descobriu Cristo deve levar os outros para ele. Uma grande alegria não se pode guardar para si mesmo. É necessário transmiti-la Papa Bento XVI"
citas[31] = "Não é o evitar o sofrimento, a fuga diante da dor, que cura o homem, mas a capacidade de aceitar a tribulação e nela amadurecer, de encontrar o seu sentido através da união com Cristo, que sofreu com infinito amor.  Papa Bento XVI"
citas[32] = "Maria é Aquela que acreditou e, do seu seio, correram rios de água viva, que vêm regar a história dos homens."
citas[33] = "Os inimigos declarados de Deus e da Igreja devem ser difamados tanto quanto se possa (desde que não se falte à verdade), sendo obra de caridade gritar: Eis o lobo!, quando está entre o rebanho, ou em qualquer lugar onde seja encontrado.- São Francisco de Sales"
citas[34] = "E eu lhes digo que o protestantismo não é cristianismo puro, nem cristianismo de espécie alguma; é pseudocristianismo, um cristianismo falso. Nem sequer tem os protestantes direito de se chamarem cristãos. - Padre Amando Adriano Lochu"
citas[35] = "MALDITOS os cristãos que suportam sem indignação que seu adorável SALVADOR seja posto lado a lado com Buda e Maomé em não sei que panteão de falsos deuses. - Padre Emmanuel"

aleatorio = Math.random() * (citas.length)
aleatorio = Math.floor(aleatorio)
document.write(citas[aleatorio])